name: ci
on:
  pull_request:
    branches:
      - next
jobs:
  test:
    name: "check_unit_tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install
      - run: yarn test
      - name: Upload Coverage
        run: npx codecov --disable=gcov
  typescript:
    name: "check_types"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install
      - run: yarn typescript
  lint:
    name: "check_lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install
      - run: yarn lint
      - run: yarn format
  docs-api:
    name: "check_docs_api"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js Env
        uses: actions/setup-node@v2
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build 🔧
        run: yarn docs-build-api
      - name: Check for API changes
        run: git diff --exit-code
